FROM python:3.10.11-slim-bullseye AS compile-image

# Multi-stage build:
# https://docs.docker.com/develop/develop-images/multistage-build/
# https://pythonspeed.com/articles/multi-stage-docker-python/

# Stage 1: Compile Python dependencies
#-------------------------------------

RUN apt update -y && \
  apt install -y --no-install-recommends \
    curl \
    unzip \
    build-essential \  
    libffi-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --upgrade pip~=23.0.1 --timeout 120 \
  && pip install --user -r requirements.txt --timeout 120

# Stage 2: Create the final image with application code
#------------------------------------------------------

FROM python:3.10.11-slim-bullseye

# Define and create non-root user
ARG USERNAME=redash
RUN useradd --create-home ${USERNAME}

# Copy Python dependencies from compile-image stage
COPY --from=compile-image /root/.local /home/${USERNAME}/.local

# Set working directory, switch to non-root user
WORKDIR /home/${USERNAME}/app/
RUN chown -R ${USERNAME} ./ /home/${USERNAME}/.local
ENV PATH=/home/${USERNAME}/.local/bin:$PATH
USER ${USERNAME}

# Install dependencies for testing
COPY etc/requirements.dev.txt ./etc/
RUN pip install --user -r ./etc/requirements.dev.txt --timeout 120

# Copy source and configurations
COPY LICENSE LICENSE.redash manage.py docker-entrypoint.sh ./
COPY migrations ./migrations/
COPY redash ./redash/
COPY tests ./tests/

# Expose port
EXPOSE 5000

# Define entrypoint and default command
ENTRYPOINT ["./docker-entrypoint.sh"]
CMD ["server"]
